project:
  type: book

book:
  title:    "DATA 5690 Class Notes"
  subtitle: "Computational Methods for FinTech"
  author:   "Dr. Tyler J. Brough"
  date:     "01/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part_one.qmd
      chapters:
        - summary.qmd
        - prob.qmd
    - part: part_two.qmd
      chapters:
        - two.qmd
    - references.qmd
  appendices:
    - appendix-b.qmd
    - appendix-c.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



