project:
  type: book

book:
  title: "DATA 5690: Midterm"
  author: "Tyler J. Brough"
  date: "2/28/2024"
  chapters:
    - index.qmd
    - frequentist.qmd
    - bayesian.qmd
    - references.qmd

bibliography: references.bib
csl: 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
