---
title: "DATA 5690: Final Project"
author: Tyler J. Brough
date: "December 4, 2024"
bibliography: biblio.bib
jupyter: python3
---

## **Introduction**

Blah, blah, blah


## **Question 2.** 

Fintech is traditionally defined as a combination of finance and technology based on big data, machine learning and artificial intelligence, and cryptocurrencies and blockchain technologies. The economist Xavier Vives as defined fintech as follows:

> _"Fintech may be understood as the use of innovative information and
automation technology in financial services. New digital technologies
automate a wide range of financial activities and may provide new and more
cost-effective products in parts of the financial sector, ranging from lending
to asset management, and from portfolio advice to the payment system."_[^1]

We note that the data scientist @JordanHDSR2019 ([see also](https://people.eecs.berkeley.edu/~jordan/)) has argued for a definition of data science as a new and emerging engineering discipline that rests upon three foundational pillars:

- __1.__ The _inferential_ from probability and statistics.

- __2.__ The _algorithmic_ from theoretical computer science.

- __3.__ The _social-institutional_ from economics.

We have argued that the third pillar should be rightly conceived of as the catallactics of the exchange paradigm from the Austrian tradition of economics. Make the strongest case you can for this latter claim for fintech as a specialization of data science in the Jordan sense with obvious ties to financial markets and institutions. Why is an economic theory that focuses on process and which explicitly incorporates the entrepreneurial role and institutional evolution required? What are the greatest limitations for the theory of catallactics in this role? Is it possible to extend or augment catallactic theory to overcome these limitations? How?

[^1]: https://blog.iese.edu/xvives/files/2018/02/EE_2.2017.pdf#page=99

\vspace{5mm}

## **Question 2.** 

Throughout this course we have argued that the focus on _market process_ and the _entrepreneur-as-arbitrageur_ is the key strength of callactic theory to serve as a fundamental theory underlying fintech. At the same time, we have noted that perhaps the greatest limitation of catallactics in serving this role is its weak foundation in probability theory. We have offered the subjective Bayesian derivation of probability due to Bruno de Finetti as a possible way to augment catallactic theory to provide the missing foundational probability theory. Ludwig von Mises - one of the founders of catallatics - emphasized the essential role of monetary calculation by the entrepreneur as the central driver of the market process. See @HorwitzRAE2004 and @HorwitzHOPE1998. 

Discuss the possibility of Mises' monetary calculation as the necessary institutional foundations for de Finetti's derivation of subjective probability. Can we properly understand de Finetti's derivation of probability as a catallactic theory? See @NauTD2001. Is the Dutch Book Theorem a catallactic theory resting upon Misesian microfoundations? See also @PressaccoZiani2010.

\vspace{5mm}

## **Question 3.** 

@CulpMillerJACF1995a [see also @CulpMillerJACF1995b] provide an academic defense of Metallgesellschaft Refining & Marketing's (MGRM) energy hedging strategy based upon the research of [Holbrook Working](https://en.wikipedia.org/wiki/Holbrook_Working). Their defense of MGRM rests on an understanding of their hedging strategy as dynamic arbitrage called _synthetic storage_ as an example of what Working called _carry-charge hedging_. Outline the basics of this strategy. What financial contracts were traded? How? (_Hint:_ you should know the difference between a stack-and-roll hedge vs a strip hedge and why it matters).

At the heart of MGRM's strategy was the creation and maintenance of novel long-term delivery contracts for heating oil and natural gas. Propose an interpretation of this strategy as a real-world example of what Nobelist [James M. Buchanan](https://en.wikipedia.org/wiki/Special:Search?go=Go&search=james+m+buchanan&ns0=1) has referred to as _creative arbitrage_. How does this strategy depend upon Misesian-Hayekian-de Finettian microfoundations? Do you find this explanation compelling? Why or why not? Defend your position with logic and evidence.

The following additional resources should be helpful (all available on Canvas):

* @CulpMillerJACF1995a *Metallgesellschaft and the Economics of Synthetic Storage* 

* @CulpMillerJACF1995b *Hedging in the Theory of Corporate Finance*

* @BuchananSEJ1964 *What Should Economists Do?* 

* @Buchanan1979  *Chapter 4 - General Implications of Subjectivism in Economics*

* @Buchanan1979 *Chapter 5 - Natural and Artifactual Man*

* @Buchanan1979  *Chapter 16 - Retrospect and Prospect*

* @Buchanan1982 *Chapter 2 - The Domain of Subjective Economics: Between Predictive Science and Moral Philosophy*


## **Question 4.** 

@PirrongJFM1997 strongly criticizes MGRM from the perspective of neoclassical (mainstream) finance theory. Pirrong's critique is based upon an understanding of hedging as exclusively defined as minimum-variance hedging for risk mitigation purposes only. Pirrong classifies MGRM's strategy as wildly "speculative" from this perspective.


- __(a)__ Pirrong's argument rests on a strong econometric foundation by which an optimal minimum-variance hedge ratio is derived. His model is called _Backwardation-Adjusted GARCH_ or _BAG_. Pirrong provides plots of the dynamics of the hedge ratio over time in Figures 1 -- 3. Comment on these dynamics. What is the pattern?  

- __(b)__ Pirrong's critique rests upon the frequentist tradition of specifying a "corrrect" model for the data-generating process. Discuss this modeling philosophy. Do you find Pirrong's empirical findings compelling regarding a specification of the true model? Are there any issues such as overfit, numerical instability, unreported competing model specifications, etc that might cause you to be skeptical? Discuss [especially in light of our discussion of @Leamer1978 and his concept of the *Axiom of Specification*]. Has Pirrong taken the *con* out of econometrics?! 

- __(c)__ In the conclusion of his paper Pirrong invokes Bayes' Rule (presumably via the Dutch Book Theorem) to suggest strong doubt regarding the possibility of MGRM's possession of an informational advantage to support an arbitrage view of their hedging strategy. Why do you think he does this? How does it connect to the reported (frequentist) econometric methods in the paper? Is there a Bayesian interpretation of these methods? If so, why didn't Pirrong simply provide a full Bayesian model? Do you find his argument convincing? Why or why not. Defend you answer with logic, evidence, and probability and econometric theory.


You may also find the following additional resources helpful (all available on Canvas):


- @Culp2004 *Chapter 14 - Hedge Ratios*

- @MurrayTAS1994 *The Drunk and Her Dog: An Illustration of Cointegration and Error Correction* 

- @Leamer1978 *Chapter 1* 

- @LeamerAER1983 *Let's Take the Con Out of Econometrics* 

- @LeamerJEP2010 *Tantalus on the Road to Asymptopia* 

- @PirrongJFM1997 *Metallgesellschaft: A Prudent Hedger Ruined, Or a Wildcatter on NYMEX?* 

\vspace{5mm}

## **Question 5.** 

@PirrongJFM1997 makes the compelling claim that whether or not MGRM's strategy was successful as @CulpMillerJACF1995a claim cannot be determined on an a priori basis but is instead an empirical question. [Bollen & Whaley (1998)](https://scholar.google.com/scholar?cluster=10820252363050604815&hl=en&as_sdt=5,45&sciodt=0,45) take this claim from Pirrong as their point of departure for their analysis. However, rather than proposing a definition of optimal hedging and imposing it upon the MGRM, Bollen & Whaley take Culp & Miller's claim at face value and evaluate the empirical success or failure of MGRM's strategy based on their own self-reported metric.

<br>

- __(a)__ Is Pirrong guilty of _lecturing birds on flying_? Why or why not. Defend your position with logic, evidence, and theory.

- __(b)__ Interpret Bollen & Whaley's _simulating supply_ model as an example of Brock et al's empirical approach. See [Brock, Lakonishok, and Lebaron (1992)](https://www.jstor.org/stable/pdf/2328994.pdf) and [Brock & de Lima (1996)](https://www.sciencedirect.com/science/article/abs/pii/S016971619614013X). Compare and contrast this approach to Pirrong's approach. How are they similar? How are they different? Can Bollen's & Whaley's approach be given a Bayesian interpretation? Can we understand the resulting simulated profit and loss distribution of MGRM's hedging strategy as a Bayesian posterior predictive density? Interpret this in light of Pirrong's rational Bayesian. Do the empirical findings of Bollen & Whaley strengthen or challenge Pirrong's Bayesian claim?

- __(c)__ Using the MLE estimates reported in Table B simulate 5k sample paths of the Bollen & Whaley model for heating oil. Plot the histogram. Discuss how to next add the hedging analysis and determine if MGRM's strategy was successful. Just describe the latter - no need to fully simulate it!

- __(d)__ Based upon [Rubin (1984)](https://www.jstor.org/stable/2240995) can you suggest a modeling strategy to make Bollen's & Whaley's analysis fully _Bayesianly justifiable_?


\newpage

# References 
